### ISSUE TITLE
[Manjaro] Question: KWallet 5, what more is needed?

### ISSUE THREAD

**Issue by agreedSkiing** [flathub/com.tutanota.Tutanota#164]
Kwallet 5 provides support for the `org.freedesktop.secrets` package since the merge of https://invent.kde.org/frameworks/kwallet/-/merge_requests/11 or some support according to the name of the merge request, but what more is needed to make Tuta in its flatpack version work with Kwallet?

Currently my system has this 

```bash
$ pacman -Q org.freedesktop.secrets
kwallet5 5.113.0-1
$ pacman -Q libsecret
libsecret 0.21.2-1
```

And when i try to run the flatpack
~~~
$ flatpak run com.tutanota.Tutanota                                                                                                   
[2:0105/192532.752622:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
the monkey has been patched pid: 2
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 19:25:32.865: Failed to load module "xapp-gtk3-module"
Gtk-Message: 19:25:32.865: Failed to load module "canberra-gtk-module"
[2:0105/192532.886003:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0105/192532.886022:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
version:   3.119.10
resolving key... tutanota-vault
config up to date
[2024-01-05T18:25:32.911Z] using safeStorage with backend gnome_libsecret
Failed to resolve/generate key:  tutanota-vault Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Nw.getPassword (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async tR.fetchKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210954)
    at async tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210682)
~~~
after pressing the error prompt ok button
~~~
[2024-01-05T18:26:51.505Z] Create tray:true
resolving key... tutanota-vault
[ApplicationWindow] webAssetsPath:  /app/lib/tutanota/resources/app.asar
[ApplicationWindow] getting dictionaries from: https://app.tuta.com/desktop//dictionaries/
default mailto handler: false
Webapp ready
[2024-01-05T18:26:51.556Z] [ElectronUpdater] DEBUG: no update info on disk, disabling updater.
[ApplicationWindow] spellcheck-dictionary-initialized en-GB
desktop file exists, checking version...
Failed to resolve/generate key:  tutanota-vault Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Nw.getPassword (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async tR.fetchKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210954)
    at async tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210682)
[DesktopWindowManager] Failed to get sseInfo $ [DeviceStorageUnavailableError]: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Nw.getPassword (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async tR.fetchKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210954)
    at async tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210682)
    at tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210855)
unable to start sse client $ [DeviceStorageUnavailableError]: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Nw.getPassword (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async tR.fetchKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210954)
    at async tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210682)
    at tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210855)
resolving key... tutanota-credentials
Failed to resolve/generate key:  tutanota-credentials Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Nw.getPassword (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async tR.fetchKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210954)
    at async tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210682)
    at async Sb.decryptUsingKeychain (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:286977)
    at async ipc (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:297195)

~~~

and then the error in the electron application
~~~
Feedback v3.119.10 - DeviceStorageUnavailableError - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.119.10
 Timestamp (UTC): Fri, 05 Jan 2024 18:26:52 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.119.10 Chrome/116.0.5845.228 Electron/26.6.2 Safari/537.36
DeviceStorageUnavailableError
 Error message: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Nw.getPassword (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async tR.fetchKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210954)
    at async tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210682)
    at async Sb.decryptUsingKeychain (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:286977)
    at async ipc (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:297195)
Stacktrace: 
DeviceStorageUnavailableError: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Nw.getPassword (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async tR.fetchKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210954)
    at async tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210682)
    at async Sb.decryptUsingKeychain (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:286977)
    at async ipc (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:297195)
    at tR.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:210855)
    at async Sb.decryptUsingKeychain (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:286977)
    at async ipc (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:5:297195)
~~~

P.S. KWallet5 dependecies
![Screenshot_20240105_201611](https://github.com/flathub/com.tutanota.Tutanota/assets/93997033/13a4ac03-0a83-47ab-8659-351c1179cabe)

**Comment by olof-nord** [comment]
Just out of curiosity, are you affected by https://github.com/flathub/com.tutanota.Tutanota/issues/141?
I am not on KDE, (im on GNOME), and that issue effectively makes running the flatpak standalone not possible for a long time unless I keep re-opening it after it crashes. 

I have a hunch that the application expects to access either the home folder, or somewhere on /etc/ and because that access is restricted, it crashes.

There is also the continuous Failed to connect to socket /run/dbus/system_bus_socket log message, I suspect that is also some missing permission.

I have experimented with the `--persist` finish-args but nothing definite so far. I am trying to understand better the Electron TypeScript code which is used to create the bundle in an effort to better understand it all.

> The --persist=path option can be used to map paths from the user’s home directory into the sandbox filesystem. This makes it possible to avoid configuring access to the entire home directory, and can be useful for applications that hardcode file paths in ~/.

https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

**Comment by olof-nord** [comment]
RIght, so at least the cause of the system dbus error I found out. It is solved by this: https://github.com/flathub/com.tutanota.Tutanota/pull/165

**Comment by agreedSkiing** [comment]
> Just out of curiosity, are you affected by #141? I am not on KDE, (im on GNOME), and that issue effectively makes running the flatpak standalone not possible for a long time unless I keep re-opening it after it crashes.

Can't test it since the flatpack version no keeps failing when i try to log in, need to purge it completely from my system.

**Comment by agreedSkiing** [comment]
Fresh install done from the terminal this time and now it seems to work after doing a complete restart of my system, I'm very confused.

So I still have the logs from the first startup after doing the `flatpak remove com.tutanota.Tutanota --delete-data -v` and this is what it does when trying to persist the user credentials.
~~~
$ flatpak run com.tutanota.Tutanota --trace-deprecation
[2:0106/171006.391954:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
the monkey has been patched pid: 2
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (node:buffer:202:11)
    at new Buffer (node:buffer:286:3)
    at /app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:11:8023
    at Object.<anonymous> (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:11:47358)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at node:electron/js2c/browser_init:2:122709
Gtk-Message: 17:10:06.509: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:10:06.509: Failed to load module "canberra-gtk-module"
[2:0106/171006.527677:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0106/171006.527692:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
version:   3.119.10
resolving key... tutanota-vault
config up to date
[2024-01-06T16:10:06.554Z] using safeStorage with backend gnome_libsecret
[2024-01-06T16:10:06.557Z] Create tray:true
[ApplicationWindow] webAssetsPath:  /app/lib/tutanota/resources/app.asar
[ApplicationWindow] getting dictionaries from: https://app.tuta.com/desktop//dictionaries/
scheduling to check sse in 1 seconds
default mailto handler: false
Webapp ready
[2024-01-06T16:10:06.577Z] [ElectronUpdater] DEBUG: no update info on disk, disabling updater.
[ApplicationWindow] spellcheck-dictionary-initialized en-GB
desktop file exists, checking version...
last missed notification check: { lastMissedNotificationCheckTime: 1704557301727 }
scheduling to check sse in 92 seconds
starting sse connection
lookup sse request
established SSE connection with code 200
received new timeout: heartbeatTimeout:240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
downloading missed notification
lookup
missed notification response 200
dl missed notification response closed
MissedNotification is empty
scheduling to check sse in 288 seconds
[2024-01-06T16:10:44.945Z] [WorkerSqlCipher] started sqlcipher-worker-1
[2024-01-06T16:10:44.968Z] [sqlcipher-worker-1] set up sql cipher done
[2:0106/171045.375227:ERROR:nss_util.cc(239)] Error initializing NSS with a persistent database (sql:/home/eriase/.pki/nssdb): NSS error code: -8126
resolving key... tutanota-credentials
key tutanota-credentials not found, generating a new one
storing push identifier
~~~

After the reboot with me exiting the application through the KDE GUI.
~~~
[2:0106/172027.322816:ERROR:nss_util.cc(239)] Error initializing NSS with a persistent database (sql:/home/eriase/.pki/nssdb): NSS error code: -8126
storing push identifier
last missed notification check: { lastMissedNotificationCheckTime: 1704557769177 }
scheduling to check sse in 46 seconds
starting sse connection
lookup sse request
established SSE connection with code 200
received new timeout: heartbeatTimeout:240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
downloading missed notification
lookup
missed notification response 200
dl missed notification response closed
MissedNotification is empty
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
[ApplicationWindow] closing offline db for userId NW64jfM----9
[2024-01-06T16:30:39.902Z] [OfflineDbRefCounter] closed db for NW64jfM----9
[2024-01-06T16:30:39.903Z] sse response error: Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7) {
  code: 'ECONNRESET'
}
sse response closed
~~~

In between my troubleshooting from my previous comment https://github.com/flathub/com.tutanota.Tutanota/issues/164#issuecomment-1879737304 I installed KeepassXC, but removed it pretty much after half an hour. So I don't know why it works now, might have been something with installing it through the terminal since I noticed that the software centre in Manjaro with KDE wanted me to download an update straight after installing com.tutanota.Tutanota or it might have something to do with me not checking the checkbox in the integrate with system prompt on the first boot.

To actually find the true solution to this I would probably need to install Manjaro 23.1.2 with KDE in a VM and tinker with it for a bit.

**Comment by olof-nord** [comment]
Thanks for the debug logs though!

That `Error initializing NSS with a persistent database` line looks like an interesting one, as well as the `sse response error` one in the end.

The flatpak Tutanota is def not in a daily driver state yet.
I have switched to the web version and am working on identifying and ironing out all problems - so far Tutanota have been pretty positive to contributions.

**Comment by agreedSkiing** [comment]
So after some tries I give up for the time being since tuta in a gnome-boxes VM with a manjaro and KDE install works fine with Kwallet with no password protection, it could be different if it had one i don't know current :), and so my only reaction is [wat](https://www.destroyallsoftware.com/talks/wat).

I have tried the flatpak and AppImage and the only errors are when exiting through the Plasma GUI with the flatpak and AppImage
~~~
[ApplicationWindow] closing offline db for userId NW64jfM----9
[2024-01-06T18:49:45.333Z] [OfflineDbRefCounter] closed db for NW64jfM----9
[2024-01-06T18:49:45.333Z] sse response error: Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7) {
  code: 'ECONNRESET'
}
sse response closed
~~~
and only with the flatpak when checking or not checking the checkbox in the picture below
~~~
Error: Command failed: touch /home/manjaro/.local/share/icons/hicolor
touch: cannot touch '/home/manjaro/.local/share/icons/hicolor': No such file or directory

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'touch /home/manjaro/.local/share/icons/hicolor'
}
stderr: touch: cannot touch '/home/manjaro/.local/share/icons/hicolor': No such file or directory
~~~
![image](https://github.com/flathub/com.tutanota.Tutanota/assets/93997033/29d72848-5e7f-48fe-807a-a31b999525c4)

and some logs 
[unchecked-integrate-with-system-flatpak-run-1.log](https://github.com/flathub/com.tutanota.Tutanota/files/13851268/unchecked-integrate-with-system-flatpak-run-1.log)
[checked-integrate-with-system-flatpak-run-1.log](https://github.com/flathub/com.tutanota.Tutanota/files/13851269/checked-integrate-with-system-flatpak-run-1.log)

One approach that I could not test in gnome-boxes is the installation from the software centre or Discover as it seems to be called. The software centre hangs the VM when the installation reaches 90% and eventually, waited 1½ hour or so, i force shutdown the VM.

**Comment by charlag** [comment]
From a cursory glance it seems like you've tried a lot of different things and secret storage providers and the data on the disk does not match the keychain anymore. I would recommend wiping both the data and the key in the keychain(s) and trying again. Any secret storage implementation should work

**Comment by agreedSkiing** [comment]
> From a cursory glance it seems like you've tried a lot of different things and secret storage providers and the data on the disk does not match the keychain anymore. I would recommend wiping both the data and the key in the keychain(s) and trying again. Any secret storage implementation should work

Yeah that seems to have fixed it for me completely
